app = "dev2next"
primary_region = "dfw"

[build]
    builder = "paketobuildpacks/builder:base"

[build.args]
    BP_JVM_VERSION = "17"

[env]
    SPRING_PROFILES_ACTIVE = "http"
    JAVA_TOOL_OPTIONS = "-XX:MaxRAMPercentage=75 -XX:+UseG1GC -XX:+TieredCompilation -XX:TieredStopAtLevel=1"

[vm]
    cpu_kind = "performance"
    cpus = 2
    memory_mb = 2048

[http_service]
    internal_port = 8080
    force_https = true
    http2 = true
    auto_stop_machines = "stop"
    auto_start_machines = true
    min_machines_running = 1
    processes = ["app"]